services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - 'POSTGRES_DB=pomodoro'
      - 'POSTGRES_PASSWORD=pomodoro'
      - 'POSTGRES_USER=pomodoro'
    volumes:
      - pomodoro_data_java:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
volumes:
  pomodoro_data_java:
